# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Poll',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='question_text',
            new_name='question',
        ),
    ]
